# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/batuh/qt_designer/QR/QRW.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 467)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ıcon/indir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#centralwidget{\n"
"\n"
"border-image: url(:/newPrefix/ıcon/988880.jpg);\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Rage Italic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_5.setObjectName("label_5")
        self.lineEdit_isim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_isim.setGeometry(QtCore.QRect(210, 100, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_isim.setFont(font)
        self.lineEdit_isim.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_isim.setText("")
        self.lineEdit_isim.setObjectName("lineEdit_isim")
        self.lineEdit_qrboyut = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_qrboyut.setGeometry(QtCore.QRect(210, 250, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_qrboyut.setFont(font)
        self.lineEdit_qrboyut.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_qrboyut.setText("")
        self.lineEdit_qrboyut.setObjectName("lineEdit_qrboyut")
        self.lineEdit_icerik = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_icerik.setGeometry(QtCore.QRect(210, 180, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_icerik.setFont(font)
        self.lineEdit_icerik.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_icerik.setText("")
        self.lineEdit_icerik.setObjectName("lineEdit_icerik")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 250, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(210, 330, 201, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_process = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_process.setGeometry(QtCore.QRect(420, 310, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_process.setFont(font)
        self.pushButton_process.setStyleSheet("background-color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 127);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../combobox/ıcon/indir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_process.setIcon(icon1)
        self.pushButton_process.setObjectName("pushButton_process")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHakkinda = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ıcon/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHakkinda.setIcon(icon2)
        self.actionHakkinda.setObjectName("actionHakkinda")
        self.menuHelp.addAction(self.actionHakkinda)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "İçerik Adresi:"))
        self.label_4.setText(_translate("MainWindow", "QR Kod İsimi:"))
        self.label_5.setText(_translate("MainWindow", "QR Kod Oluşturucu"))
        self.label_2.setText(_translate("MainWindow", "QR Kod Boyutu:"))
        self.pushButton_process.setText(_translate("MainWindow", "Oluştur"))
        self.menuHelp.setTitle(_translate("MainWindow", "Yardım"))
        self.actionHakkinda.setText(_translate("MainWindow", "Hakkında"))

import icons_rc
